# This file may be used to create a conda environment using:
# $ mamba env create -f <this file>

name: gprMax-devel
dependencies:
- python>3.7
- colorama
- cython
- h5py
- jinja2
- jupyter
- matplotlib
- numpy
- pip
- psutil
- scipy
- mpi4py
- pyopencl
- humanize
- numpy-stl
- terminaltables
- tqdm

- pip:
  # - pycuda
  - git+https://github.com/craig-warren/PyEVTK.git


# brew install mpich